name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Cache pnpm store
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test
